config/routes.rb
Rails.application.routes.draw do
  resources :numbers
  # get 'home/index'
  # get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
    root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/number.rb
class Number < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  before_action :set_number, only: %i[ show edit update destroy ]

  # GET /numbers or /numbers.json
  def index
    @numbers = Number.all
  end

  # GET /numbers/1 or /numbers/1.json
  def show
  end

  # GET /numbers/new
  def new
    @number = Number.new
  end

  # GET /numbers/1/edit
  def edit
  end

  # POST /numbers or /numbers.json
  def create
    @number = Number.new(number_params)

    respond_to do |format|
      if @number.save
        format.html { redirect_to number_url(@number), notice: "Number was successfully created." }
        format.json { render :show, status: :created, location: @number }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /numbers/1 or /numbers/1.json
  def update
    respond_to do |format|
      if @number.update(number_params)
        format.html { redirect_to number_url(@number), notice: "Number was successfully updated." }
        format.json { render :show, status: :ok, location: @number }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /numbers/1 or /numbers/1.json
  def destroy
    @number.destroy!

    respond_to do |format|
      format.html { redirect_to numbers_url, notice: "Number was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_number
      @number = Number.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def number_params
      params.require(:number).permit(:name, :phone1, :phone2, :phone3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
    <%= link_to 'Home', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "Number List", numbers_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Add Number", new_number_path, class:"nav-link" %>
        </li>
        </ul>
    </div>
    </div>
</nav>

app/views/home/index.html.erb
<h1>Welcome</h1>
<h3>Ruby on rails website to add phone numbers</h3>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Phone Numbers</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/numbers/_form.html.erb
<%= form_with(model: number) do |form| %>
  <% if number.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(number.errors.count, "error") %> prohibited this number from being saved:</h2>

      <ul>
        <% number.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :name, class: "form-control", placeholder: "Name"%>
  </div>

  <div class="mb-3">
    <%= form.text_field :phone1, class: "form-control", placeholder: "Phone Number 1" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :phone2, class: "form-control", placeholder: "Phone Number 2" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :phone3, class: "form-control", placeholder: "Phone Number 3" %>
  </div>

  <br/>

  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/numbers/_number.html.erb
<div id="<%= dom_id number %>">
  <p>
    <strong>Name:</strong>
    <%= number.name %>
  </p>

  <p>
    <strong>Phone1:</strong>
    <%= number.phone1 %>
  </p>

  <p>
    <strong>Phone2:</strong>
    <%= number.phone2 %>
  </p>

  <p>
    <strong>Phone3:</strong>
    <%= number.phone3 %>
  </p>

</div>

app/views/numbers/edit.html.erb
<h1>Editing number</h1>

<br>

<%= render "form", number: @number %>

<br>

<div>
  <%= link_to "Back", numbers_path, class:"btn btn-secondary" %>
  <%= link_to "Show", @number, class:"btn btn-primary" %>
</div>

app/views/numbers/index.html.erb
<h1>Number List</h1>

<table class="table table-striped table">
  <thead>
    <tr>
      <th>Name</th>
      <th>1st Phone Number</th>
      <th>2nd Phone Number</th>
      <th>3rd Phone Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @numbers.each do |number| %>
      <tr>
        <td><%= number.name %></td>
        <td><%= number.phone1 %></td>
        <td><%= number.phone2 %></td>
        <td><%= number.phone3 %></td>
        <td><%= link_to "Show", number, class:"btn btn-success" %></td>
        <td><%= link_to "Edit", edit_number_path(number), class:"btn btn-warning" %></td>
        <td><%= link_to "Delete", number, class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete #{number.name}?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/numbers/new.html.erb
<h1>New number</h1>

<br>

<%= render "form", number: @number %>

<br>

<div>
  <%= link_to "Back", numbers_path, class:"btn btn-primary" %>
</div>

app/views/numbers/show.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold"><%= @number.name %></h1>
      <strong>1st Phone Number:</strong>
      <%= @number.phone1%>
    </p>
    <div>
    <p>
      <strong>2nd Phone Number:</strong>
      <%= @number.phone2%>
    </p>
    <p>
      <strong>3rd Phone Number:</strong>
      <%= @number.phone3%>
    </p>
    <br/>
      <%= link_to "Back", numbers_path, class:"btn btn-secondary" %>
      <%= link_to "Edit", edit_number_path(@number), class:"btn btn-warning" %>
    </div>
  </div>
</div>